version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    environment:
      RABBITMQ_DEFAULT_USER: mqadmin
      RABBITMQ_DEFAULT_PASS: 1111
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ~/env/docker/mq-container/volumes/rabbitmq-local/enabled_plugins:/etc/rabbitmq/enabled_plugins